config:
  framework: "hardhat" 
  framework_version: "^2.19.4" 
  node_version: "20" 
  package_manager: "yarn"

environments:
  ETHERSCAN_API_KEY: "ABC123ABC123ABC123ABC123ABC123ABC1"
  MAINNET_URL: "https://rpc.ankr.com/eth"
  HERMEZ_URL: "https://zkevm-rpc.com"
  GOERLI_URL: "https://rpc.ankr.com/eth_goerli"
  SEPOLIA_URL: "https://rpc.sepolia.org"
  MAINNET_FORK_10540_URL: "https://rpc.ankr.com/eth_mainnet"
  MAINNET_FORK_10547_URL: "https://rpc.ankr.com/eth_mainnet"
  MAINNET_FORK_10548_URL: "https://rpc.ankr.com/eth_mainnet"
  HARDHAT_FORK_URL: "https://rpc.ankr.com/eth_mainnet"
  PHALCON_FORK_ID: "ABC123ABC123ABC123ABC123ABC123ABC1"
  PHALCON_RPC_ID: "ABC123ABC123ABC123ABC123ABC123ABC1"
  PHALCON_CHAIN_ID: "ABC123ABC123ABC123ABC123ABC123ABC1"
  PHALCON_FORK_ACCESS_KEY: "ABC123ABC123ABC123ABC123ABC123ABC1"
  PRIVATE_KEY_MAINNET: "0xabc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc1"
  PRIVATE_KEY_HERMEZ: "0xabc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc1"
  PRIVATE_KEY: "0xabc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc1"
  PROXY: "https://proxy.dedge.xyz"
  REPORT_GAS: "true"

tasks:
  install-dependencies:
    - git init
    - yarn install